# Generated by Django 3.1.7 on 2021-03-13 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210227_1127'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=400)),
                ('phone', models.CharField(default='', max_length=400)),
                ('email', models.CharField(default='', max_length=400)),
                ('desc', models.CharField(max_length=300)),
            ],
        ),
    ]
